@extends('layouts.app')
@section('title','Yocolab')

@section('content')
    <section class="inner_page_breadcrumb">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 offset-xl-3 text-center">
                    <div class="breadcrumb_content">
                        <h4 class="breadcrumb_title">Privacy Policy</h4>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{url('/')}}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Privacy Policy</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>

<section class="about-page">
    
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-12 col-md-12">
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;border:none;border-bottom:solid #4F81BD 1.0pt;padding:0cm 0cm 4.0pt 0cm;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:0cm;border:none;padding:0cm;font-size:35px;font-family:"Montserrat", sans-serif;color:#17365D;'>Privacy Policy</p>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;color:black;'>Thanks for visiting YOCOLAB.com!! Please take a moment to read our privacy policy before using our website.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;color:black;'>This Privacy Policy describes our policies and procedures on the collection, use, disclosure, and sharing of your personal information when you use this website.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>By using our website, you agree and understand that the information and material contained in this website implies and constitutes your consent to the terms and conditions mentioned below.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><strong><em><span style="font-size:18px;line-height:115%;">UNDER NO CIRCUMSTANCE WE SHALL HAVE ANY ACCOUNTABILITY TO YOU FOR ANY LOSS OR DAMAGE AS A RESULT OF THE USE OF THE ON ANY INFORMATION PROVIDED ON THE SITE. YOUR USE OF THE SITE&nbsp;AND YOUR RELIANCE ON ANY INFORMATION ON THE SITE&nbsp;IS COMPLETELY AT YOUR OWN RISK.</span></em></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Our collection, use, disclosure, and processing of personal information about individuals will vary depending upon the circumstances. This privacy notice is intended to describe our overall privacy and data protection practices. In some cases, different or additional notices about our data collection and processing practices may be provided and apply to our processing of certain personal information</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 1 - WHY WE COLLECT YOUR INFORMATION</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>We use the information , we collect in various ways, including:</span></p>
<ul style="list-style-type: disc;">
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Provide, operate, and maintain our website</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Improve, personalize, and expand our website</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Understand and analyze how you use our website</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Develop new products, services, features, and functionality</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Send you emails</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Find and prevent fraud</span></li>
</ul>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 2 -&nbsp;OUR COLLECTION OF PERSONAL INFORMATION</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Generally, we collect your personal information on a voluntary basis. However, if you decline to provide certain personal information that is marked mandatory, you may not be able to access certain Services or we may be unable to fully respond to your inquiry.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Personal information that we collect and process will vary depending upon the circumstances. We collect personal information directly from individuals, automatically related to the use of the Services, and in some cases, from third parties (such as social networks, platform providers, payment processors, data providers, and operators of certain third party services that we use). For example, some of the ways we collect information are as follows:</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><em><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Information we collect directly.&nbsp;We collect information that you provide to us, such as:</span></em></p>
<ul style="list-style-type: disc;">
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>when you provide contact information, and send other personal information to us;</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>when you complete or submit a form through YOCOLAB.com , for example, &quot;Contact Us&quot; or &ldquo;More Information&rdquo; forms;</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>When you register for an account;</span></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:36.0pt;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>When you register for an Account on our website, we may ask for your personal information</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>The personal information we may ask:</span></p>
<ul style="list-style-type: disc;">
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>First Name</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Last Name</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Age</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Email&nbsp;</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Address</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Phone Number</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Educational Qualification</span></li>
    <li><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Payment details</span></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:36.0pt;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>&nbsp;</h2>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 3 - HOW WE USE YOUR PERSONAL INFORMATION</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>While the purposes for which we may process personal information will vary depending upon the circumstances, in general we use personal information for the purposes set forth below. Where GDPR or other relevant laws apply, we have set forth the legal bases for such processing in parenthesis&nbsp;</span></p>
<ol style="list-style-type: decimal;margin-left:15.100000000000001px;">
    <li><strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Providing support and services</span></strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>: including, for example, to provide products and services you request (and send related information), operate YOCOLAB.com ; to communicate with you about your access to and use of our services; to respond to your inquiries; to provide troubleshooting, fulfil your requests and provide technical support; and for other customer service and support purposes.&nbsp;</span></li>
    <li><strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Analyzing and improving our business:</span></strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>&nbsp;including to better understand how users access and use YOCOLAB.com, to evaluate and improve our services and business operations, and to develop new features, offerings, and services; to conduct surveys, and other evaluations, such as customer satisfaction surveys; and for other research and analytical purposes.&nbsp;</span></li>
    <li><strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Personalizing content and experiences:</span></strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>&nbsp;including to provide or recommend features, content, social connections, and referrals; tailor content we send or display on YOCOLAB.com ; to offer location customization and personalized help and instructions; and to otherwise personalize your experiences.&nbsp;</span></li>
    <li><strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Advertising, marketing and promotional purposes:</span></strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp;including to reach you with more relevant ads and to evaluate, measure, and improve the effectiveness of our ad campaigns; to send you newsletters, offers, or other information we think may interest you; to contact you about YOCOLAB.com &nbsp;or information we think may interest you;&nbsp;</span></li>
    <li><strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Defending our legal rights:</span></strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>&nbsp;including to manage and respond to actual and potential legal disputes and claims, and to otherwise establish, defend or protect our rights or interests, including in the context of anticipated or actual litigation with third parties.&nbsp;</span></li>
    <li><strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Complying with legal obligations:&nbsp;</span></strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>including to comply with the law, our legal obligations and legal process, such warrants, subpoenas, court orders, and regulatory or law enforcement requests.&nbsp;</span></li>
</ol>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>&nbsp;</h2>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 4 - DISCLOSURE OF PERSONAL INFORMATION</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>We may disclose the personal information that we collect about you as set forth below or as otherwise described at the time of collection or sharing.</span></p>
<ol style="list-style-type: decimal;margin-left:8px;">
    <li><strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Service providers:</span></strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp;We may disclose personal information with third-party service providers who use this information to perform services for us, such as hosting providers, instructors, advisors, consultants, and customer service and support providers.</span></li>
    <li><strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Third Parties:</span></strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp; We employ other companies and individuals to perform functions on our behalf. Examples include sending postal mail and e-mail, removing repetitive information from customer lists, analyzing data, providing marketing assistance, processing payments, transmitting content, and providing customer service. These third-party service providers have access to personal information needed to perform their functions, but may not use it for other purposes.</span></li>
    <li><strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Business transfers:</span></strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp;We may disclose or transfer personal information as part of any actual or contemplated merger, sale, and transfer of our assets, acquisition, financing or restructuring of all or part of our business, bankruptcy or similar event, including related to due diligence conducted prior to such event where permitted by law.</span></li>
    <li><strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Legally required:</span></strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp;We may disclose personal information if we are required to do so by law (e.g., to law enforcement, courts or others, e.g., in response to a subpoena or court order).</span></li>
    <li><strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;font-family:"Montserrat", sans-serif;font-size:13.5pt;'>Protect our rights:</span></strong><span style='line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp;We may disclose personal information where we believe it necessary to respond to claims asserted against us or, comply with legal process (e.g. warrants), enforce or administer our agreements and terms, for fraud prevention, risk assessment, investigation, and to protect the rights, property, or safety of us, our clients and customers or others.</span></li>
</ol>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 5 - COOKIES, TRACKING, AND ANALYTICS</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>We may use first party and third-party cookies, pixel tags, plugins, and other tools to gather device, usage and browsing information when users &nbsp;visit YOCOLAB.com . For instance, when you visit this website , our server may record your IP address (and associated location information) and other information such as the type of your internet browser, your Media Access Control (MAC) address, computer type (Windows or macOS), screen resolution, operating system name and version, device manufacturer and model, language, and the pages you view and links you select on the Services, as well as date and time stamps associates with your activities on YOCOLAB.com.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>We use the information for security purposes, to facilitate navigation, to personalize and improve your experience while using the Services, to improve and measure our advertising campaigns and to better reach users with relevant advertising both on YOCOLAB.com &nbsp;and on third party websites. We also gather statistical information about use of the Services in order to continually improve their design and functionality, understand how they are used and assist us with resolving questions regarding them.</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 6 - COOKIES</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Cookies are small text files that a website transfers to your hard drive to store and sometimes collect information about your usage of websites, such as time spent on the websites, pages visited, language preferences, and other anonymous traffic data. You can control the way in which cookies are used by altering your browser settings. You may refuse to accept cookies by activating the setting on your browser that allows you to reject cookies. However, if you select such a setting, this may affect the functioning of YOCOLAB.com . Unless you have adjusted your browser setting so that it will refuse cookies, our system will issue cookies when you access or log on to our Service.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><strong><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Essential cookies</span></strong><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp;are essential, as they enable you to move around the Service and use its features. Without these cookies we could not, for example, authenticate your login or remember that you are logged-in as you move through the website.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><strong><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Functionality cookies</span></strong><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp;allow us to remember choices you make (such as the region you&apos;re in) and tailor the Service to provide enhanced features and content for you. For instance, they can be used to remember your login details or remember your nickname when you next login. They may also be used to provide services you&apos;ve requested, for example leaving a comment on the Service.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><strong><em><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;color:black;'>We may use the following types of cookies:</span></em></strong></p>
<ul style="margin-bottom:0cm;" type="disc">
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;color:black;'><strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>Security</span></strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>: These cookies allow us to secure access to your account.</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;color:black;'><strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>Preference</span></strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>: These cookies are used to store your preferences like language choice and display of search results.</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;color:black;'><strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>Analytics</span></strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>: We track traffic patterns so we can identify popular content and potential problems.</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;color:black;'><strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>Features</span></strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>: We may also use cookies to split some users into test groups to test new features.</span></li>
    <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;color:black;'><strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>Advertising</span></strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>: We use non-identifiable information about you to show you advertising on our services and third party sites.</span></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>If you have disabled one or more cookies, we may still use information collected from cookies before your disabled preference was set. However, we will stop using the disabled cookie to collect any further information.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-family:"Montserrat", sans-serif;font-weight:bold;'><span style='font-size:24px;line-height:115%;font-family:"Montserrat", sans-serif;'>SECTION 7 -</span></span> <span style='font-family:"Montserrat", sans-serif;font-weight:bold;'><span style='font-size:24px;line-height:115%;font-family:"Montserrat", sans-serif;'>PIXEL TAGS AND OTHER SIMILAR TECHNOLOGIES</span></span><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Pixel tags (also known as web beacons and clear GIFs) may be used in connection with some Websites to, among other things, track the actions of users of the Websites (including email recipients), measure the success of our marketing campaigns and compile statistics about usage of the Websites and response rates. We and our service providers may also use pixel tags in HTML emails to our customers, to help us track email response rates, identify when our emails are viewed, track whether our emails are forwarded, and conduct analytics.</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 8 - LOG FILES</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Most browsers collect certain information, such as your IP address, device type, screen resolution, operating system version and internet browser type and version. This information is gathered automatically and stored in log files.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 9 - THIRD PARTY ANALYTICS TOOLS</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Our Website may use automated devices and applications operated by third parties, such as Google Analytics, which uses cookies and similar technologies to collect and analyze information about use of the Websites and report on activities and trends. This service may also collect information regarding the use of other websites, apps and online resources.&nbsp;</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 10 - DO-NOT-TRACK SIGNALS</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Please note that our Websites do not recognize or respond to any signal which your browser might transmit through the so-called &apos;Do Not Track&apos; feature your browser might have. If you wish to disable cookies on our Websites, you should not rely on any &apos;Do Not Track&apos; feature your browser might have.</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 11 - SECURITY</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>We use technical, administrative, and physical controls in place to help protect Personal information from unauthorized access, use, and disclosure. Even so, despite our reasonable efforts, no security measure is ever perfect or impenetrable. In the event that the security of your account has been compromised, please immediately notify us by visiting (&ldquo;Contact Us&rdquo;).</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 12 - DO NOT SELL MY DATA</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Except as otherwise stated in this Privacy Policy, we do not sell, trade, rent or otherwise share for marketing purposes your Personal Information with third parties without your consent.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>We will only process your Personal Data if we have a lawful basis for doing so. Lawful bases for processing include consent, contractual necessity and our &ldquo;legitimate interests&rdquo; or the legitimate interest of others, as further described below. In some cases, we process Personal Data based on the consent you expressly grant to us at the time we collect such Personal Data. &nbsp;When we process Personal Data based on your consent, it will be expressly indicated to you at the point and time of collection. From time to time, we may also need to process Personal Data to comply with a legal obligation, if it is necessary to protect the vital interests of you or other data subjects, or if it is necessary for a task carried out in the public interest.</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 13 - HOW WE PROTECT YOUR INFORMATION</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>Your account is protected by your account password and we urge you to take steps to keep your personal information safe by not disclosing your password and by logging out of your account after each use. However, these measures do not guarantee that your information will not be accessed, disclosed, altered or destroyed by breach of such firewalls and secure server software. By using our Service, you acknowledge that you understand and agree to assume these risks.</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 14 - DATA RETENTION</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>We will retain your personal information for the period necessary to fulfill the purposes outlined in this privacy notice unless a longer retention period is required or permitted by law. We may retain personal information for longer where required by our legal and regulatory obligations, professional indemnity obligations, or where we believe it is necessary to establish, defend or protect our legal rights and interests or those of others. With respect to the data and files we handle as a processor, we retain this personal information in accordance with our clients&rsquo; instructions.</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 15 - CCPA Privacy Rights (Do Not Sell My Personal Information)</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>Under the CCPA, among other rights, California consumers have the right to:</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>Request that a business that collects a consumer&apos;s personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'>
    <ul style="margin-bottom:0cm;list-style-type: disc;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-family:"Montserrat", sans-serif;'>Request that a business deletes any personal data about the consumer that a business has collected.</span></li>
    </ul>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'>
    <ul style="margin-bottom:0cm;list-style-type: disc;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-family:"Montserrat", sans-serif;'>Request that a business that sells a consumer&apos;s personal data, not sell the consumer&apos;s personal data.</span></li>
    </ul>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 16 - GDPR Data Protection Rights</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>The right to access &ndash;</span></strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;You have the right to request copies of your personal data. We may charge you a small fee for this service.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>The right to rectification &ndash;</span></strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>The right to erasure &ndash;</span></strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;You have the right to request that we erase your personal data, under certain conditions.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>The right to restrict processing &ndash;</span></strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;You have the right to request that we restrict the processing of your personal data, under certain conditions.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>The right to object to processing &ndash;</span></strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;You have the right to object to our processing of your personal data, under certain conditions.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>The right to data portability &ndash;</span></strong><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;font-family:"Montserrat", sans-serif;'>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 17 - THIRD-PARTY WEBSITES</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>The Services may contain links to third-party services. We do not own, operate, or control the websites of third-parties, including those of independently owned and operated franchisees. Accordingly, this Policy does not apply to any services maintained or operated by third-parties. When you click on those links, you will go to a third-party website where you will be subject to that service&rsquo;s privacy policy or similar statement and terms of use, and we encourage you to read that policy statement. We are not responsible for the privacy practices of other services, and we expressly disclaim any liability for their actions, including actions related to the use and disclosure of personal information by those third parties.</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 18 - CHANGES TO THIS POLICY</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>We may amend this Policy at any time. If we make any material change in how we collect, use, disclose, or otherwise process personal information, we will prominently post a notice regarding such change on the Services. Any material changes to this Policy will be effective 10 days after our posting of the updated Policy or as otherwise required by applicable law. Where required to do so by law, we may seek your prior consent to any material changes we make to this Policy.</span></p>
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-family:"Montserrat", sans-serif;'>SECTION 19 - CONTACT US</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>If you have any questions or concerns about this Policy, please contact us using the following contact information:&nbsp;</span>contact@yocolab.com</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'><span style='font-size:18px;line-height:115%;font-family:"Montserrat", sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Montserrat", sans-serif;'>&nbsp;</p>

</div>
</div>
</div>
</section>
@endsection